language: php
sudo: false

php:
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then vendor/bin/phpunit --coverage-clover build/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --diff --dry-run --using-cache=no; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then php vendor/bin/php-coveralls -v -x build/clover.xml -o build/clover.json; fi

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "KzIouxyjF/v6pEkMNn4K9khaEJq468Itl8TH8NYiJ3A4nbOT9u9AhgV8lL7h/HAlgz55DD/HG72w3Yg6/OvzZX0ex7LNQgYKmNUQlGzGizgL5ck8OW19VyVAKsJDbvQZDAJA+w0ghBtuwAuvKsUNkpG/94K3k7KhJJq9+qrV7Ueja9o7y4kqercS35YRvlNTlBdbLeLThwPj4x1CQUfdw9GT1uRQ4/JuovLSiQoBUwVaTKNxVr5897qkASJW2JQb+XFLCYD6CmtAXLNOitTao32AvNERWCNf0qnvwpT4XRc8gCLsfxGCPcSLOkRIoif11kg/ZgIETzw5BCE2yy1itIFYBPVv8VgwRYkYkjttBjpoZ9YbUccGMnK7tYXmIQThHq2nuBxYpNy0u2bWGpZkZuMgpKBkYNpRgcgUbTdTkRtj5HNwqLF/4xMRcB1R4G7ohRFRjAn3Tb2yWgiG3uyvhwz3Qb1hbNeLVFWzQjUtgV4Y7LSkwjzVnjPaleAlBHk8cfH8kgZhGdGl4b90tFpBovWNqxmnngqJOWZqhhVA8pD9DuN+kQK2DMBgbh8QnTFERL9jKIriJXmN8hQy73IqjmiSTuZ8REiTWTMK3Qnm9RXJZhfidFhmLKOoiJ/DEcwmPXRcDbEL8zaSqVpQgIMasCYZCP3EDe9thgfqUr65GJ0="
